### ISSUE TITLE
How do i config the Mod?

### ISSUE THREAD

**Issue by lyhras** [Baijson/Baconators#11]
I installed the mod via Twitch into a existing Modpack (Forever Stranded) but only the baconator show up.
Also i tried to config it in Minecraft via the "Mod Options..." but i cant click configure.
Is there a file that i need to edit?

1.10.2

Thanks

**Comment by Baijson** [comment]
You can enable and configure additional baconators in the baconators.cfg file.

When in the twitch app, open the modpack profile,
Hit the button with the 3 dots on the right hand side, next to "Website" and "Get more content" a popup menu will appear. Hit "Open Folder".
Inside Windows Explorer that just opened, go into the config folder, and look for baconators.cfg
