### ISSUE TITLE
Items with extra ID at the end are not being filled

### ISSUE THREAD

**Issue by hErbsDK** [Baijson/Baconators#3]
Playing FTB Presents Skyfactory 2.5 at the moment, and the baconator config is by default set to include TConstruct:jerky, and it's "children" .. e.g.: TConstruct.jerky:1

I haven't looked through your code, as I am both too tired and not savy enough (I think), but it seems that it's not being checked for?

The mod version is 1.3 in the default pack, but I have tried to update to 2.0.2 (latest on Curse) - I had to do a little c/p to the new config, since it seems it's been changed a bit (for the better though :))

I don't know if it will be possible to add this further distinction, as I doubt TConstruct are the only ones using this method to organize similar items under the same ID.

Let me know if you need to see the config. I have put things the right place, 'cause I've checked with some of the other entries that do not have the distinction , and they work fine.

I have tried to find information on the official MC wiki, but I can't seem to find out what it's actually called when you do this distinction.

I hope this isn't too messy ...

**Comment by Baijson** [comment]
Hello! 

Are you playing SkyFactory 2.5.0 with an updated version of this mod? 
Have you tried using a comma, like so:  TConstruct:jerky,1 etc.

Current config file in SkyFactory 2.5.2 with Baconators 2.0.2 looks like this:  [https://gist.github.com/Baijson/c067fff044e7b1bdbc09905af8d13bc6](url) and works.

**Comment by hErbsDK** [comment]
Thanks for the answer :) .. No I havent' tried with comma .. it might not have been updated on the FTB client yet maybe .. Is this documented somewhere to use the commas? .. I am however glad that the mod creator has adressed the issue :). 

Again .. thanks .. I hope it wasn't too stupid :P .. Nice little mod btw - Simple, effective and a fun name too hehe .. Keep up the good work

**Comment by Baijson** [comment]
Youre welcome! The use of comma's was added in 2.0.0 i added it in the changelogs. 
I still have to document it somewhere, but irl has been a bit busy.

thanks for the compliment! Enjoy!
