### ISSUE TITLE
Mod images are cluttered with irrelevant metadata

### ISSUE THREAD

**Issue by curiosity-a** [Baijson/Baconators#5]
It looks like significant volumes of data were added to each image by Adobe Fireworks. This affects both all textures and the screenshot. When saved with Paint.NET, the size of each texture went down to about 1 kB (from about 50 kB) and the size of the screenshot went down to about 250 kB (from about 750 kB).

**Comment by Baijson** [comment]
Thanks. Will be addressed in the next update, along with the update to 1.11.2
